server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      ## 单机版本配置自己的地址,
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      ## 集群版本配置其它服务的地址, eureka7002.com 在 hosts 中配置
      defaultZone: http://eureka7002.com:7002/eureka

